name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm -r exec tsc -p tsconfig.json --noEmit
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
